title: "Will's Blog"
email: tvminh.it@gmail.com
description: >- # Multiline description
  Personal blog about technology, programming, and software development.
baseurl: ""
url: "" # Add your site URL here
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Will
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Pagination
paginate: 30
paginate_path: "/page/:num/"

# Feed settings
feed:
  path: feed.xml
  posts_limit: 10
  categories:
    - Jekyll
    - tutorial

# SEO settings
twitter:
  username: your-twitter-handle
  card: summary_large_image
social:
  name: Will
  links:
    - https://twitter.com/your-twitter-handle
    - https://github.com/your-github-handle
    - https://linkedin.com/in/your-linkedin-handle

# Analytics
google_analytics: G-YGVERCPPXP

# Authors
authors:
  will:
    name: Will
    display_name: Will
    avatar: 'assets/images/will.png'
    email: tvminh.it@gmail.com
    description: "Blog's author."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-compose

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE.txt

# Include files
include:
  - _pages

# Sass processing
sass:
  style: compressed
  sourcemap: never