name: Daily Python Script

on:
  schedule:
    - cron: '50 23 * * *'  # This means every day at 23:50 UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have dependencies

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # Pass the secret as an environment variable
        run: python script.py

      - name: Configure Git
        run: |
          git config --local user.email "tvminh.it@gmail.com"
          git config --local user.name "GitHub Action Bot"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated update of markdown posts" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}